### PR TITLE
Add recruits 2020

### PR DESCRIPTION
**Pull request by JoshiNaman**
The previous PR had too many changes and commits that made it difficult to follow. I have made changes to only the member section in this PR and added photos. Other changes wrt alumni and mentor section will be made later in the other PR.

### CODE REVIEW

**Comment by Sarath18** [comment]
Thank you for the changes. Please update the images that were mentioned [here](https://github.com/Project-MANAS/projectmanas.in/pull/16#issuecomment-689827343) and fix the following broken GitHub links (these are the updated links):

Abhineet: https://github.com/abhichou4
Gokul: https://github.com/gokulp01

**Comment by Sarath18** [comment]
Mentor and Alumni updates to the team page in a follow-up PR will be appreciated.

**Comment by shrijitsingh99** [comment]
This looks great :+1:
Just one last thing could you upload these pictures to imgur instead of GitHub, since it will just bloat the repository. Will ping you with the credentials.

**Comment by JoshiNaman** [comment]
> This looks great 
> Just one last thing could you upload these pictures to imgur instead of GitHub, since it will just bloat the repository. Will ping you with the credentials.

Okay, sure.

**Review by Sarath18 — COMMENTED** [review]
Thank you, the changes look good. Verified all the image links :heavy_check_mark: 

Just had a question, do the images take a significantly longer time to load on the website? (when not using cache) or is it just for me?

**Comment by JoshiNaman** [comment]
> Thank you, the changes look good. Verified all the image links ✔️
> 
> Just had a question, do the images take a significantly longer time to load on the website? (when not using cache) or is it just for me?

I cleared my cache and tried the same. There is a problem with image loading. On further reading imgur's T&C, they don't allow people to hotlink the photos for content on other websites. 
A link is attached for the same:
https://support.awesome-table.com/hc/en-us/articles/360008772720-Why-are-images-from-Imgur-displayed-as-broken-links-

Should we stick with GitHub for now and later try other ways of storing images?

**Comment by shrijitsingh99** [comment]
> Should we stick with GitHub for now and later try other ways of storing images?

Let's stick to this, for now, we can migrate to AWS later. We should have an updated website at least for now.
Image loading will not work when running it on localhost, change the server address to something else for it to work.

Just a note for the future, try and compress images to around 100kb, to reduce page load time.

@Sarath18 Please give a final look, and merge it in if all is good.

**Comment by Sarath18** [comment]
@shrijitsingh99 how about moving all the senior members to the top, i.e. right after the division heads?

Everything else looks good to me.

**Comment by shrijitsingh99** [comment]
Oh yeah, can you edit that if you have time else will do it tonight.

**Comment by shrijitsingh99** [comment]
Moving ahead, since the call was made by the team to group the profiles based on division.

**Pull request merged**
